extender_codes: Malonyl-CoA
job_name: Fostriecin
molecule: C[C@@](/C=C/[C@H]1CC=CC(=O)O1)([C@@H](C[C@H](/C=C\C=C/C=C/CO)O)OP(=O)(O)O)O
offload_mech: cyclization
output_dir: RetroTideV2/krswaps/results
starter_codes: Methylmalonyl-CoA
stereo: all
