job_name: Cryptofolione
molecule: C1C=CC(=O)O[C@H]1/C=C/C[C@H](C[C@@H](/C=C/C2=CC=CC=C2)O)O
output_dir: RetroTideV2/krswaps/results
starter_codes: cin
extender_codes: Malonyl-CoA
stereo: all
offload_mech: cyclization