job_name: Rapamycin
molecule: C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[C@H](C(=O)[C@@H]([C@@H](/C(=C/[C@H](C(=O)C[C@H](OC(=O)[C@@H]3CCCCN3C(=O)C(=O)[C@@]1(O2)O)[C@H](C)C[C@@H]4CC[C@H]([C@@H](C4)OC)O)C)/C)O)OC)C)C)/C)OC
output_dir: RetroTideV2/krswaps/results
starter_codes: DHCH-CoA
extender_codes: Malonyl-CoA, Methylmalonyl-CoA
stereo: all
offload_mech: thiolysis